# Header
menu:
  Home: http://www.argibay.org/
  Quienes Somos: http://www.argibay.org/nosotros/
  Vida: /vida/
  Obra: /obra/
  Cartas: /cartas/
  Prensa: /prensa/
  Artículos: /articulos/
  Redes Sociales: /sociales/
  Contacto: /contacto/

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
# - recent_posts
- toc

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - tagcloud
  - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-88860633-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
